config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"r
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  accepts_nested_attributes_for :movie
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
  validates :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new; @bookmark.build_movie
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.new(title: bookmark_params[:movie_attributes][:title], overview: bookmark_params[:movie_attributes][:overview], rating: bookmark_params[:movie_attributes][:rating])
    @movie.save!
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.movie = @movie
    @bookmark.save!
    redirect_to lists_path
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:list_id, :comment, movie_attributes: [:overview, :rating, :title])
  end
end

app/controllers/lists_controller.rb
require 'json'
require 'open-uri'
require 'net/http'
require 'date'

class ListsController < ApplicationController
  def index
    today = Time.new
    api_key = "5eb2852848f013dccdd6edab04d61358"
    url = URI("https://api.themoviedb.org/3/discover/movie?include_adult=false&language=en-US&page=1&primary_release_date.gte=#{today.strftime("20%y-%m-%d")}&primary_release_date.lte=#{today.year}-12-31")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["Authorization"] = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1ZWIyODUyODQ4ZjAxM2RjY2RkNmVkYWIwNGQ2MTM1OCIsInN1YiI6IjYyZTIyZGZjMDIxY2VlMDA1NTAyYzhjNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.O0bbqdpLmsohFuhBo1Mtmb28xDpO4GP6Jutbbqv0f6Q'
    response = http.request(request)
    parsedData = JSON.parse(response.read_body)
    dataArray = parsedData["results"]
    movie_titles = []
      dataArray.each { |element| movie_titles.push({ title: element["title"], date: convert_date(element["release_date"]), poster: element["poster_path"]}) }
    @upcoming_movies = movie_titles.sort_by { |i| Date.parse i[:date] }.last(20).uniq
    @lists = List.all
    @lists.each do |list|
      list.average_rating = calculate_average_rating(list.id)
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def calculate_average_rating(list_id)
    ((Bookmark.joins(:movie).where(list_id: list_id).pluck(:rating).sum) / (Bookmark.joins(:movie).where(list_id: list_id).pluck(:rating).size)).round
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  private

  def convert_date(arr)
    date_arr = arr.split("-")
    "#{date_arr[2]}/#{date_arr[1]}/#{date_arr[0]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="d-flex flex-row bg-dark form-container" data-controller="search" data-search-api-key-value=<%= ENV['MOVIE_API_KEY'] %>>
  <div class="bookmark-form">
    <h1>New Bookmark</h1>
    <div>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment  %>
        <%= f.simple_fields_for :movie do |a| %>
        <%= a.input :title, input_html: { data: {action: "keydown->search#searchMovies", search_target:"input"} } %>
        <%= a.input :overview %>
        <%= a.input :rating, collection: 1..10 %>
        <% end %>
        <%= f.submit "Add bookmark", class: "button" %>
      <% end %>
    </div>
  </div>
  <div class="flex-grow-1">
  <h1 class="ms-5 mt-" id="search-result-title">Search results</h1>
    <ul id="results"
    data-search-target="results"
    class="resultsList mt-3"
    >
  </div>
  <div class="modal" tabindex="-1" id="movieModal" data-search-target="movie">
  <div class="backdrop"></div>
      <div class="modal-dialog">
        <div class="modal-content bg-dark">
          <div class="modal-header d-flex justify-content-around align-items-center">
              <h4 class="modal-title">Modal title</h4>
              <h4 class="modal-rating"></h4>
          </div>
          <div class="modal-body">
            <div id="typed-strings"></div>
          </div>
          <div class="modal-footer">
            <button type="button" class="close-button" data-bs-dismiss="modal" data-action="click->search#closeModal">Close</button>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Minder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script type=’text/javascript’ src=’config.js’></script>
    <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Bebas Neue">
</head>

  <body>
    <nav class="d-flex flex-row align-items-center justify-content-around bg-dark">
        <h1 class="text-center my-3 heading"><%= link_to "Movie Minder", root_path, class: "text-decoration-none" %></h1>
        <i class="fa-solid fa-film fa-5x" style="color: #fad900;"></i>
    </nav>

    <div class="hero d-flex flex-column justify-content-end align-items-center">
      <h3 class="display-4">Remember your memorable movies!</h3>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_future_card.html.erb
<div class="futureCard">
  <%= image_tag "https://image.tmdb.org/t/p/w200/#{movie[:poster]}" %>
  <div class="mx-4">
    <p><%= movie[:title]%></p>
    <p>Release date: <%= movie[:date] %></p>
  </div>
</div>

app/views/lists/_list_card.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="card list-card my-2 flex-row justify-content-around align-items-center">
    <% if list.photo.attached? %>
      <%= cl_image_tag list.photo.key, width: 200, height: 200, crop: :fill, class: "rounded p-3" %>
    <% else %>
      <p>You haven't uploaded an image</p>
    <% end %>
    <div>
      <p>Total number of movies: <%= list.bookmarks.count %></p>
      <p>Average rating: <%= list.average_rating %> / 10</p>
    </div>
    <div class="d-flex flex-column flex-grow-1 align-items-end">
      <h3><%= list.name %></h3>
      <button class="my-3 button"><%= link_to "See more", list_path(list), class: "text-decoration-none"%></button>
      <button class="btn btn-danger text-decoration-none"><%= link_to "Delete", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none color text-light btn-lg" %></button>
    </div>
  </div>

app/views/lists/index.html.erb
<div class="d-flex flex-row justify-content-around bg-dark ">
  <ul class="mt-3">
  <div class="list-header">
    <h1>Your movie lists</h1>
    <%= link_to "Add a new list", new_list_path, class: "btn btn-flat btn-success btn-lg" %>
  </div>
    <% @lists.each do |list| %>
      <%= render partial: "list_card", locals: {list: list} %>
    <% end %>
</div>
  </ul>
    <div class="card mt-4 mx-5 d-flex flex-column justify-content-start futureCard-container">
      <div>
        <h1>Upcoming movies</h1>
      </div>
      <div class="d-flex justify-content-center">
      <ul>
        <% @upcoming_movies.each do |movie| %>
          <%= render partial: "future_card", locals: {movie: movie} %>
        <% end %>
      </ul>
      </div>
    </div>
</div>

app/views/lists/new.html.erb
<div class="bg-dark">
  <div class="list-form-container bg-dark">
    <h1>New List</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="bookmark-list-container d-flex flex-column align-items-start bg-dark">
  <h1 class="list-title m-4"><%= @list.name %></h1>
  <ul>
    <% @list.bookmarks.each do |bookmark| %>
    <li>
      <div class="movie-card">
        <h2><%= bookmark.comment %></h2>
        <p><%= @movies.find(bookmark.movie_id).title %></p>
        <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?"}, class:"btn btn-danger"  %>
      </div>
    </li>
    <% end %>
  </ul>
  <div class="ms-4">
    <button class="button m-1"><%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class:"text-decoration-none" %></button>
    <button class="button m-2"><%= link_to "Return to homepage", lists_path, class:"text-decoration-none" %></button>
  </div>
</div>